#ifndef feed_system_harness_fuel_hotfire_acc_types_h_
#define feed_system_harness_fuel_hotfire_acc_types_h_
typedef struct P_feed_system_harness_fuel_hotfire_T_
P_feed_system_harness_fuel_hotfire_T ;
#endif
